[workspace]
members = [".", "src/bitcoin", "src/rollup", "src/common"]

[package]
name = "shadowBTC"
type = "bin"
authors = ["mohammed7s"]

[dependencies]
bitcoin = { path = "src/bitcoin" }
rollup = { path = "src/rollup" }

[[test]]
name = "test"
path = "src/test.nr"